### ISSUE TITLE
the data set

### ISSUE THREAD

**Issue by LJBLKR** [lilygeorgescu/3d-super-res-cnn#5]
Could you please provide me with the compressed package of the data set, likely in your C:\\Research\\SR\\medical images\\

**Comment by lilygeorgescu** [comment]
hi,

Here (https://drive.google.com/file/d/13dow-J95YTnJwLvznfVBnzeUoUm005IJ/view?usp=sharing) you have a copressed package with NAMIC.

I have also added the matlab script in order to get our own patches (on namic dataset or other dataset).

I cannot give you the CH dataset due to privacy issues.

Have a nice day.
